export let ship = [
{
      id: 0,
      name: "Serendipity",
      tonnage: 450,
      number_of_passengers: 320,
      tonnage_price: 3205,
    },
    {
      id: 1,
      name: "Imagination",
      tonnage: 650,
      number_of_passengers: 120,
      tonnage_price: 5200,
    },
    {
      id: 2,
      name: "Liberty",
      tonnage: 540,
      number_of_passengers: 126,
      tonnage_price: 2346,
    },
    {
      id: 3,
      name: "Wanderlust",
      tonnage: 40,
      number_of_passengers: 16,
      tonnage_price: 1684,
    },
    {
      id: 4,
      name: "Gale",
      tonnage: 50,
      number_of_passengers: 12,
      tonnage_price: 345,
    },
    {
      id: 5,
      name: "Zephyr",
      tonnage: 580,
      number_of_passengers: 146,
      tonnage_price: 1235,
    },
    {
      id: 6,
      name: "Sapphire",
      tonnage: 40,
      number_of_passengers: 16,
      tonnage_price: 487,
    },
    {
      id: 7,
      name: "Amazonite",
      tonnage: 50,
      number_of_passengers: 12,
      tonnage_price: 2456,
    },
    {
      id: 8,
      name: "Atlantis",
      tonnage: 580,
      number_of_passengers: 146,
      tonnage_price: 2367,
    },
];
